export enum PreferencesCategories {
    Arts = 1,
    Beach,
    Entertainment,
    FamilyTravel,
    Gastro,
    HistoricalContent,
    Mountain,
    Outdoors,
    Recreation,
    Skiing,
    ArtGallery,
    Exhibit,
    PerformingArtsVenue,
    PublicArt,
    Arcade,
    BowlingAlley,
    Casino,
    ComedyClub,
    ConcertHall,
    DiscGolf,
    GoKartTrack,
    KaraokeBox,
    LaserTag,
    MiniGolf,
    MovieTheater,
    PoolHall,
    GolfCourse,
    Circus,
    Aquarium,
    WaterPark,
    Zoo,
    Playground,
    Pool,
    DiveSpot,
    SpiritualCenter,
    MemorialSite,
    Museum,
    HistoricalSite,
    Castle,
    Palace,
    Campground,
    Cave,
    Hill,
    HotSpring,
    NAturePreserve,
    Park,
    PedestrianPlaza,
    Waterfall,
    Volcan,
    Vineyard,
    NationalPark,
    PaintballField,
    BikeTrail,
    Rafting,
    RecreationCenter,
    RockClimbingSpot,
    SkiArea,
    ApresSkiBar,
    SkiChairlift,
    SkiChalet,
    SkiLodge,
    SkiTrail,
    GeneralEntertainment,
    OtherGreatOutdoors,
    ThemePark
}

export enum RecommenderModelEnum {
    CollaborativeFiltering = 0,
    ContentBased = 1,
    KnowledgeBased = 2,
    TopCitiesOnTravel = 3
}

export enum CityTabEnum {
    description = '0',
    pointsOfInterests = '1',
    flights = '2',
    hotels = '3',
    ratings = '4',
    recommendationForYou = '5'
}