export const SAVE_USER_PREFERENCES = '@Main/SAVE_USER_PREFERENCES';
export const CONTINUE_CLICKED = '@Main/CONTINUE_CLICKED';
export const SELECT_CITIES = '@Main/SELECT_CITIES';
export const GET_CITIES_CHOOSER = '@Main/GET_CITIES_CHOOSER';
export const GO_TO_PREFERENCES = '@Main/GO_TO_PREFERENCES';